# Generated by Django 3.0.5 on 2020-04-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('idStatus', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(max_length=1)),
            ],
        ),
    ]
