# Generated by Django 3.0.5 on 2020-04-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20200415_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='changes',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('timestamp', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='status',
        ),
    ]
