# Generated by Django 3.0.5 on 2020-04-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_auto_20200415_2030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='changes',
            new_name='Change',
        ),
    ]
