# Generated by Django 3.0.5 on 2020-04-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_auto_20200415_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='value',
        ),
        migrations.AddField(
            model_name='change',
            name='level',
            field=models.FloatField(default=999.999),
        ),
    ]
