# Generated by Django 3.0.5 on 2020-04-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_auto_20200416_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.FloatField(default=999.999)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
